# [AGC:FILE] tool=Cc author=fangkun date=2026-08-24
"""LangGraph 状态图定义：开发-测试-修复循环。"""
# [AGC:START] tool=Cc author=fangkun
from __future__ import annotations

import sys
from pathlib import Path

# 添加当前目录到 Python 路径
_current_dir = Path(__file__).parent.resolve()
if str(_current_dir) not in sys.path:
    sys.path.insert(0, str(_current_dir))

import json
import os
from typing import Any

from langchain_core.messages import AIMessage, HumanMessage, SystemMessage
from langgraph.graph import END, StateGraph

from agents import create_developer_agent, create_tester_agent
from config import Config
from models import (
    AgentState,
    BugItem,
    BugSeverity,
    IterationRecord,
    LLMReviewResult,
    TestResult,
    WorkflowStatus,
)
from prompts import (
    DEVELOPER_SYSTEM_PROMPT,
    FIX_SYSTEM_PROMPT,
    TESTER_SYSTEM_PROMPT,
)


def build_graph(config: Config) -> StateGraph:
    """构建 LangGraph 状态图。"""
    workflow = StateGraph(AgentState)

    workflow.add_node("develop", develop_node)
    workflow.add_node("test_and_evaluate", test_and_evaluate_node)
    workflow.add_node("fix", fix_node)

    workflow.set_entry_point("develop")

    workflow.add_conditional_edges(
        "test_and_evaluate",
        evaluate_condition,
        {
            "fix": "fix",
            "done": END,
        },
    )

    workflow.add_edge("develop", "test_and_evaluate")
    workflow.add_edge("fix", "test_and_evaluate")

    return workflow.compile()


def develop_node(state: AgentState) -> dict[str, Any]:
    """开发节点：Agent1 根据设计文档生成代码。"""
    # 使用 get 方法并提供默认值，避免 KeyError
    design_doc = state.get("design_doc", "")
    requirement = state.get("requirement", "")
    iteration = state.get("iteration_count", 0)

    # 如果没有设计文档，从 messages 中提取（LangGraph API 调用方式）
    if not design_doc and state.get("messages"):
        # 尝试从第一条消息中提取设计文档
        first_msg = state["messages"][0] if state["messages"] else None
        if first_msg and hasattr(first_msg, "content"):
            design_doc = first_msg.content

    # 检查是否是文件路径，如果是则读取文件内容
    if design_doc and os.path.exists(design_doc):
        try:
            with open(design_doc, "r", encoding="utf-8") as f:
                design_doc = f.read()
            print(f"[develop_node] 已读取设计文档: {len(design_doc)} 字符")
        except Exception as e:
            print(f"[develop_node] 读取文件失败: {e}")

    # 如果仍然没有设计文档，返回错误
    if not design_doc:
        return {
            "messages": [AIMessage(content="错误: 缺少设计文档。请在输入中提供 design_doc 字段或通过消息传递。")],
            "status": WorkflowStatus.FAILED.value,
        }

    if iteration == 0:
        prompt_content = DEVELOPER_SYSTEM_PROMPT.format(
            design_doc=design_doc,
            requirement=requirement,
        )
    else:
        prompt_content = DEVELOPER_SYSTEM_PROMPT.format(
            design_doc=design_doc,
            requirement=requirement,
        )

    print(f"[develop_node] 开始调用 Developer Agent (iteration={iteration})")
    developer_agent = create_developer_agent(Config())
    result = developer_agent.invoke({
        "messages": [HumanMessage(content=prompt_content)]
    })

    ai_message = result["messages"][-1]
    print(f"[develop_node] Agent 响应长度: {len(ai_message.content)} 字符")

    code_artifact = _extract_code_from_response(ai_message.content)
    print(f"[develop_node] 提取到 {len(code_artifact)} 个代码文件")

    output_dir = state.get("output_dir", "./output")
    _save_code_to_workspace(code_artifact, output_dir)

    return {
        "code_artifact": code_artifact,
        "iteration_count": iteration,
        "messages": [AIMessage(content=f"[Round {iteration}] Code generated by developer")],
    }


def test_and_evaluate_node(state: AgentState) -> dict[str, Any]:
    """测试与评估节点：Agent2 生成测试、运行测试、审查代码。"""
    code_artifact = state.get("code_artifact", {})
    iteration = state.get("iteration_count", 0) + 1
    review_dims = state.get("review_dimensions", ["correctness", "quality", "edge_cases"])

    if not code_artifact:
        return {
            "messages": [AIMessage(content="错误: 没有可测试的代码文件")],
            "status": WorkflowStatus.FAILED.value,
        }

    code_files_str = "\n\n".join(
        f"--- {path} ---\n{content}" for path, content in code_artifact.items()
    )

    dimension_details = _format_review_dimensions(review_dims)

    tester_prompt = TESTER_SYSTEM_PROMPT.format(
        code_files=code_files_str,
        review_dimensions=", ".join(review_dims),
        review_dimension_details=dimension_details,
    )

    tester_agent = create_tester_agent(Config())
    result = tester_agent.invoke({
        "messages": [HumanMessage(content=tester_prompt)]
    })

    ai_message = result["messages"][-1]
    test_result, review_result = _parse_tester_response(ai_message.content)

    # 运行 pytest
    output_dir = state.get("output_dir", "./output")
    pytest_result = _run_pytest(output_dir)
    if pytest_result:
        test_result = pytest_result

    bug_list = [bug.to_dict() for bug in review_result.bugs]

    record = IterationRecord(
        round_number=iteration,
        test_result=test_result,
        review_result=review_result,
    )

    history = list(state.get("iteration_history", []))
    history.append(record.to_dict())

    critical = review_result.critical_count
    high = review_result.high_count

    status = WorkflowStatus.IN_PROGRESS.value
    if critical == 0 and high == 0:
        status = WorkflowStatus.PASSED.value

    return {
        "iteration_count": iteration,
        "test_results": test_result.to_dict(),
        "bug_list": bug_list,
        "iteration_history": history,
        "status": status,
        "messages": [AIMessage(content=f"[Round {iteration}] Test completed: {test_result.passed} passed, {test_result.failed} failed, {critical} CRITICAL, {high} HIGH")],
    }


def fix_node(state: AgentState) -> dict[str, Any]:
    """修复节点：Agent1 根据 bug 列表修复代码。"""
    code_artifact = state.get("code_artifact", {})
    bug_list = state.get("bug_list", [])
    iteration = state.get("iteration_count", 0)
    design_doc = state.get("design_doc", "")

    if not bug_list:
        return {
            "messages": [AIMessage(content="错误: 没有 bug 列表可供修复")],
            "status": WorkflowStatus.FAILED.value,
            "iteration_count": iteration,
        }

    code_files_str = "\n\n".join(
        f"--- {path} ---\n{content}" for path, content in code_artifact.items()
    )

    bug_list_str = json.dumps(bug_list, ensure_ascii=False, indent=2)

    fix_prompt = FIX_SYSTEM_PROMPT.format(
        code_files=code_files_str,
        bug_list=bug_list_str,
        design_doc=design_doc,
    )

    developer_agent = create_developer_agent(Config())
    result = developer_agent.invoke({
        "messages": [HumanMessage(content=fix_prompt)]
    })

    ai_message = result["messages"][-1]
    updated_code = _extract_code_from_response(ai_message.content)

    # 合并更新的代码
    merged_code = {**code_artifact, **updated_code}
    _save_code_to_workspace(updated_code, state.get("output_dir", "./output"))

    return {
        "code_artifact": merged_code,
        "iteration_count": iteration,  # 保持当前迭代次数，让 test_and_evaluate 递增
        "messages": [AIMessage(content=f"[Round {iteration}] Code fixed by developer")],
    }


def evaluate_condition(state: AgentState) -> str:
    """条件评估：决定进入 fix 还是 done。"""
    status = state.get("status", WorkflowStatus.IN_PROGRESS.value)
    iteration = state.get("iteration_count", 0)
    max_rounds = state.get("max_rounds", 5)

    # 如果已经通过或失败，结束循环
    if status == WorkflowStatus.PASSED.value:
        return "done"

    if status == WorkflowStatus.FAILED.value:
        return "done"

    # 达到最大轮数，强制结束
    if iteration >= max_rounds:
        return "done"

    return "fix"


def _extract_code_from_response(content: str) -> dict[str, str]:
    """从 Agent 响应中提取代码块。"""
    code_artifact = {}
    lines = content.split("\n")
    current_file = None
    current_code = []
    in_code_block = False

    for line in lines:
        if line.startswith("```") and not in_code_block:
            in_code_block = True
            current_code = []
            continue
        if line.startswith("```") and in_code_block:
            in_code_block = False
            if current_file:
                code_artifact[current_file] = "\n".join(current_code)
            current_file = None
            continue

        if in_code_block:
            current_code.append(line)
        elif line.strip().startswith("# file:") or line.strip().startswith("# File:"):
            current_file = line.strip().split(":", 1)[-1].strip().strip("`")

    return code_artifact


def _parse_tester_response(content: str) -> tuple[TestResult, LLMReviewResult]:
    """解析 Tester Agent 的响应。"""
    test_result = TestResult()
    review_result = LLMReviewResult()

    try:
        json_start = content.find("{")
        json_end = content.rfind("}") + 1
        if json_start >= 0 and json_end > json_start:
            data = json.loads(content[json_start:json_end])

            tr = data.get("test_results", {})
            test_result = TestResult(
                passed=tr.get("passed", 0),
                failed=tr.get("failed", 0),
                errors=tr.get("errors", 0),
                total=tr.get("total", 0),
                details=tr.get("details", []),
                raw_output=tr.get("raw_output", ""),
            )

            review_data = data.get("review", {})
            bugs = []
            for b in review_data.get("bugs", []):
                severity_str = b.get("severity", "LOW").upper()
                try:
                    severity = BugSeverity(severity_str)
                except ValueError:
                    severity = BugSeverity.LOW
                bugs.append(BugItem(
                    severity=severity,
                    description=b.get("description", ""),
                    file=b.get("file", ""),
                    line=b.get("line", 0),
                ))
            review_result = LLMReviewResult(
                bugs=bugs,
                summary=review_data.get("summary", ""),
            )
    except json.JSONDecodeError:
        review_result = LLMReviewResult(
            bugs=[BugItem(
                severity=BugSeverity.HIGH,
                description="Tester response could not be parsed",
            )],
            summary="Parse error",
        )

    return test_result, review_result


def _format_review_dimensions(dims: list[str]) -> str:
    """格式化审查维度描述。"""
    dimension_map = {
        "correctness": "Functional Correctness: Does the code implement all features? Are edge cases handled?",
        "quality": "Code Quality: PEP 8, type safety, error handling, naming, organization",
        "edge_cases": "Edge Cases: Null values, empty inputs, boundary conditions, exceptions",
    }
    return "\n".join(
        f"- **{d}**: {dimension_map.get(d, d)}" for d in dims
    )


def _save_code_to_workspace(code_artifact: dict[str, str], output_dir: str) -> None:
    """保存代码到工作目录。"""
    workspace = os.path.join(output_dir, "code")
    os.makedirs(workspace, exist_ok=True)

    for filepath, content in code_artifact.items():
        full_path = os.path.join(workspace, filepath)
        os.makedirs(os.path.dirname(full_path), exist_ok=True)
        with open(full_path, "w", encoding="utf-8") as f:
            f.write(content)


def _run_pytest(output_dir: str) -> TestResult | None:
    """在工作目录运行 pytest。"""
    import subprocess

    workspace = os.path.join(output_dir, "code")
    if not os.path.exists(workspace):
        return None

    try:
        result = subprocess.run(
            ["python", "-m", "pytest", "-v", "--tb=short"],
            cwd=workspace,
            capture_output=True,
            text=True,
            timeout=60,
        )

        return TestResult(
            raw_output=result.stdout + "\n" + result.stderr,
        )
    except Exception:
        return None
# [AGC:END]
